### ISSUE TITLE
[EPIC] Knuu Testing

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#1033]
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1035
- [ ] https://github.com/rollkit/rollkit/issues/1034
- [ ] https://github.com/rollkit/rollkit/issues/920
```
