### ISSUE TITLE
[EPIC] P2P Blocksync Tracking Issue: Phase 2

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1076]
```[tasklist]
### Implementation
- [ ]  Modify `SubmitBlock` to `SubmitBlobs` in the DA interface such that it accepts a list of blocks instead of one block.
- [ ] Update the DA interface implementations -`mock`, `GRPC`, and `celestia` DA implementations to use the updated interface.
- [ ] Add a `pendingBlocks` field in Block Manager that gets blocks added to it.
- [ ] Move the call to `submitBlockToDA` from `publishBlock` to `AggregationLoop` with a separate timer according to `DABlockTime` that uses `pendingBlocks`as an argument and resets it.
- [ ] Make the option to use BlobAPI's `Submit` method configurable so a user can choose whether to use BlobAPI's `Submit` vs  `SubmitPayForBlob` in StateAPI.

```
