### ISSUE TITLE
[EPIC] P2P Blocksync Tracking Issue: Phase 3

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1110]
- [ ] Benchmarks for go-header
- [ ] Add load tests to discover the lowest block time that can be supported for different configurations
- [ ] Larger Network tests
- [ ] Plan how to support subsecond blocks - 399 ms

**Comment by Manav-Aggarwal** [comment]
Closing in favor of other tests
