### ISSUE TITLE
[EPIC] Metrics

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1126]
# Overview

We should expose metrics for rollup developers so that they can make informed decisions about their rollup. These metrics could then be viewed in something like a grafance dashboard. 

```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1129
- [ ] Add basic metrics endpoint
- [ ] Add additional metrics
```

Some metrics requested: 

- DA cost/burn rate
- Current DA batch signer’s wallet balance
- What are latest DA bundle submitted, are they successful, etc.
