### ISSUE TITLE
[EPIC] DA layer refactoring

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#1195]
To simplify DA integration implementation, we need to refactor DA layer.

Currently rollkit operates on Go interface that operates on blocks. It is possible to integrate DAs, but it can be tricky and lead to dependency hell.

New solution should:
 * be credibly neutral - API needs to be generic and allow usage of any DA
 * clearly separate dependencies in a way that can be reused easily (without dependency hell)
 * encourage developers to create DA integrations as separate projects (not inside rollkit repo)
 * separate domains - DA interface operate on blobs, shares, proofs, etc, not blocks, headers, transactions, etc.
 * enable communication with DA implementation via RPC

Proposed architecture is described in #1122.

```[tasklist]
### Tasks - new DA repo
- [ ] https://github.com/rollkit/go-da/issues/2
- [ ] https://github.com/rollkit/go-da/issues/3
- [ ] https://github.com/rollkit/go-da/issues/5
- [ ] https://github.com/rollkit/go-da/issues/4
- [ ] https://github.com/rollkit/go-da/issues/6
- [ ] https://github.com/rollkit/go-da/issues/10
```

```[tasklist]
### Tasks - rollkit
- [x] Create new implementation of existing `DataAvailabilityLayerClient`using new DA interface
- [x] Setup mock DA testing via new DA interface
- [x] Remove all old DA implementations
- [x] Simplify the code to use new DA interface instead of old one
```

```[tasklist]
### Tasks - new celestia DA implementation
- [x] Create & setup repository
- [x] Implement new DA interface
- [x] Add integration tests
- [x] Create a standalone app serving new interface
```

**Comment by chandiniv1** [comment]
@tzdybal we have written  DA-adapter for avail and rollkit team has suggested to have a separate repository to overcome dependency issues. I'm not sure of how to separate,I'm thinking like

- rollkit will import go-da package which contains da interface(client)
- we need to implement the dalc methods written in go-da package(server)
- we need to interact to rollkit via rpc

correct me If I'm wrong

**Comment by tzdybal** [comment]
Yes, the flow you described is correct.

To make it easier for developers, avoid reinventing the wheel, etc, we're [working on gRPC proxy](https://github.com/rollkit/go-da/pull/14). It designed to easily execute da-interface via gRPC.

As we're still working on the code, there is no docs yet, but you can take a look at [unit test of proxy](https://github.com/rollkit/go-da/pull/14/files#diff-8d5bed61a3c0b7b0bfdd65dd4c93e647568b1a402840f5e302c0c922f6c58ea3R17-R22) or [code of the server](https://github.com/rollkit/celestia-da/pull/7/files#diff-be50eea1cb25676ee0174ac676bd0dde49d2609e0257ed6987b923f6866b3d36R78-R88) in PR in celestia-da repo.

[`proxy.NewServer`](https://github.com/rollkit/go-da/blob/17e0ce611290bda8b4c4172ea3e1e3214804e2d4/proxy/server.go#L13) can be used to create gRPC server exposing any implementation of go-da interface. Then what you need is to create listener and pass it to `Serve` method.

https://github.com/rollkit/celestia-da/blob/bbafe6e9ffdc50e9834efd72290efed4f8dbf54d/cmd/celestia-da/main.go#L78-L88

**Comment by chandiniv1** [comment]
@tzdybal thank you for sharing the info, do we exactly require the endpoints that matches with the generic go-da interface methods(get,getall,commit,etc) or is there any alternative as currently we have endpoints for only submitting and retrieving blocks

**Comment by tzdybal** [comment]
Current prototype in rollkit is not using `Commit` and `Validate` methods. It also ignores `[]Proof` returned by `Submit`.
You could implmement `Get`, `GetIDs`, `Submit` without proofs, and this should work fine in rollkit (but will fail some unit tests provided by go-da).

**Comment by chandiniv1** [comment]
@tzdybal  Do ` GetIDs` return the commitments of the blobs in one block or  you need to address specific blobs, maybe even not in the same block, and commitments to those blobs
