### ISSUE TITLE
[EPIC] Polaris integration issues

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#1594]
Following issues will be revisited after Polaris V2 becomes available and rollkit integrates w/ it.

- [x] https://github.com/rollkit/rollkit/issues/1529
- [x] https://github.com/rollkit/rollkit/issues/1561
- [x] https://github.com/rollkit/rollkit/issues/1439

**Comment by androolloyd** [comment]
At Last (github.com/LastL2) we're looking to pick up the polaris mantle, would love to know what you need to get these integration issues sorted.

Capital, Dev resources, let me know, can ping me back here or at x.com/androolloyd

**Comment by Manav-Aggarwal** [comment]
Closing this issue since Rollkit now has support for Omni Octane and BeaconKit EVMs. Please reopen if Polaris becomes relevant again.
