### ISSUE TITLE
[EPIC] Code Hygiene

### ISSUE THREAD

**Issue by yarikbratashchuk** [rollkit/rollkit#1644]
```[tasklist]
### List of code quality issues 
- [ ] State current state of light node in docs
- [ ] In the NodeConfig, enhance readability by grouping similar items:
   - [ ]     ---- Group DA-related fields together
   - [ ]     ---- Group Aggregator related fields together
   - [ ]     ---- Add a linter that enforces grouping
   - [ ]     ---- Add an ability to read these settings from the config file, to make it easier when upstreamed
- [ ] Explore removing `dalcKV`
- [ ] At the beginning of `OnStart()`, cancel node context if there’s an error
- [ ] In Aggregation Loop, can flip logic in lazy `if-else` condition
- [ ] Explore removing redundant `context err == nil` checks
- [ ] Modify sleep logic in lazy block production mode in AggregationLoop:
  - [ ]     ---- Use `m.conf.Blocktime` instead of hardcoded 1 second
  - [ ]     ---- Implement `getRemainingSleep(start)`
  - [ ]     ---- Add a `checkpointBlockTimer` that checks in and produces an empty block
  - [ ]     ---- Add a test case for new timer logic
- [ ] Add a comment explaining why `err != nil` returns nil in `publishBlock`
- [ ] https://github.com/rollkit/rollkit/issues/1772
- [ ] Combine `headerCh` and `blockCh` into a single channel for `headerPublishLoop`
- [ ] In non-lazy mode, adjust error handling in `publishBlock` to try producing a block sooner instead of waiting a full block time
- [ ] Remove unnecessary `select` statement in `processNextDABlock` before sending to `blockInCh`
- [ ] Change `fetchErr == nil` condition to `fetchErr ≠ nil` in `processNextDABlock`
- [ ] Address inconsistency between `RetrieveLoop` and `BlockStoreRetrieveLoop` in sending blocks into `blockInCh`
- [ ] Update initialization of `lastBlockStoreHeight` to start from stored height instead of 0 in `BlockStoreRetrieveLoop`
- [ ] Update the docstring of `SyncLoop` to more accurately describe its functionality
- [ ] https://github.com/rollkit/rollkit/issues/1771
- [ ] https://github.com/rollkit/rollkit/issues/1591
- [ ] https://github.com/rollkit/rollkit/issues/1648
- [ ] https://github.com/rollkit/rollkit/issues/1642
- [ ] https://github.com/rollkit/rollkit/issues/1345
- [ ] https://github.com/rollkit/rollkit/issues/796
- [ ] https://github.com/rollkit/go-execution-abci/issues/21
- [ ] https://github.com/rollkit/go-execution-abci/issues/18
- [ ] https://github.com/rollkit/rollkit/issues/1569
- [ ] https://github.com/rollkit/rollkit/issues/654
- [ ] https://github.com/rollkit/rollkit/issues/882
```
