### ISSUE TITLE
[EPIC] Testing Cleanup

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1731]
```[tasklist]
### Improvements
- [ ] #954 
- [ ] Make test helpers proper t.Helper() functions
- [ ] Use t.Cleanup() over defer statements
- [ ] https://github.com/rollkit/rollkit/issues/621
- [ ] https://github.com/rollkit/rollkit/issues/1345
- [ ] https://github.com/rollkit/rollkit/issues/719
```

```[tasklist]
### Test Specifics
- [ ] #936 
- [ ] #956 
- [ ] #1730 
```

**Comment by tac0turtle** [comment]
completed a lot of the clean up with the recent changes
