### ISSUE TITLE
[EPIC] Kurtosis

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1733]
Looking into building out kurtosis with docker compose underneath to allow for flexibility between kurtosis, knuu, etc. 

```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1744
- [ ] https://github.com/rollkit/rollkit/issues/1755
- [ ] https://github.com/rollkit/rollkit/issues/1767
- [ ] https://github.com/rollkit/rollkit/issues/1777
- [ ] https://github.com/rollkit/rollkit/issues/1775
- [ ] Move EVM tutorial to Kurtosis
- [ ] Evaluate need for Knuu in CI vs Kurtosis in CI
- [x] MVP kurtosis docker compose with local da within repo
- [x] MVP kurtosis docker compose with local da - published image
- [x] Set up ready condition for GM kurtosis
- [ ] https://github.com/rollkit/.github/pull/12
- [ ] https://github.com/rollkit/local-da/pull/21
- [ ] https://github.com/rollkit/gm/pull/96
- [ ] Block Explorer
- [ ] Facuet
- [ ] Run the Cosmwasm Testnet with Kurtosis package
- [ ] https://github.com/rollkit/rollkit/pull/1773
```

**Comment by MSevey** [comment]
Need to publish docker image for local-da then test. 

If it works, a follow up would be to have CI for building docker image as part of the release flow on the local-da repo

**Comment by MSevey** [comment]
Closing due to issue with persisted data on kurtosis.
