### ISSUE TITLE
[EPIC] GM Tutorial Kurtosis Package

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1744]
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1743
- [ ] https://github.com/rollkit/gm/pull/96
- [ ] https://github.com/rollkit/docs/pull/414
- [x] Create version release of GM and update docker image
- [ ] ~~Add block explorer to GM Kurtosis package~~
```
