### ISSUE TITLE
[EPIC] Kurtosis Package for Cosmwasm Tutorial

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1755]
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1763
- [ ] https://github.com/rollkit/rollkit/issues/1766
- [ ] https://github.com/rollkit/docs/pull/418
- [x] Tutorial Updated
```
