### ISSUE TITLE
Cosmwasm Kutosis Package

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1763]
Goal is to spin up the cosmwasm chain in one line. 

Then the tutorial is just focused on the contract portion of it. 
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/cosmwasm/pull/1
- [x] Reduce size of docker image
- [x] Fully dockerize the contract creation to eliminate rust installation?
```
