### ISSUE TITLE
[EPIC] Kurtosis Package for Wordle Tutorial

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1767]
Goal will be to show how to build the kurtosis package for the wordle app and then run the wordle app with kurtosis. 

```[tasklist]
### Tasks
- [x] Run through current Wordle Tutorial
- [x] Update to latest rollkit
- [x] Build out kurtosis package
- [ ] https://github.com/rollkit/docs/pull/422
```
