### ISSUE TITLE
[EPIC] Tutorial Testing in CI for release

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1775]
Each tutorial should have an end state repo with CI. If the tutorial itself doesn't have the steps to generate the end state, the repo README should have them. 

Each end state repo should follow the standard repo setup:
* branch protection
* require CI
    * testing
    * linting
    * pushes, pr, tags
* project automation
* review assignment 
* dependabot --> rollkit

Goal is that on rollkit repo releases, the release would propagate out to these tutorial repos. PRs would be opened up by dependabot, and the CI would run. Then on merge and passing CI, the docs would be updated. 

```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1934
- [ ] https://github.com/rollkit/go-execution-abci/issues/43
- [ ] CosmWasm Tutorial Repo CI
- [ ] https://github.com/rollkit/rollkit/issues/1872
- [ ] MVP of building an ignite chain and running rollkit start with local DA in CI
```
