### ISSUE TITLE
[EPIC] Kurtosis DA Packages

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1777]
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1803
- [ ] Avail Kurtosis Package
- [ ] DA Kurtosis Package Template
```
