### ISSUE TITLE
Review Release Version Flow

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1799]
We have a number of downstream components between the sdk start repo and the kurtosis packages that need to be updated when a new version is released. We should review how each of them are updated and make sure that automation needs/opportunities are documented. 
```[tasklist]
### Tasks
- [x] Verify all repos are properly set up with Dependabot
- [x] Enable release on merge for all repos leading up to rollkit
- [ ] https://github.com/rollkit/rollkit/issues/1865
```

**Comment by MSevey** [comment]
Waiting on next Rollkit release for creating the checklist

**Comment by MSevey** [comment]
## Tracking steps for v0.14.1 release (WIP)
- Create v0.14.1-rc.0 tag in rollkit repo
- create draft PR in cosmos-sdk-start repo that pulls in the rc tag
- test tutorials with rollkit v0.14.1-rc.0 tag. for ignite apps add `go get github.com/rollkit/cosmos-sdk-start@bump-rollkit-v0.14.1-rc.0` step to test pulling in the latest versions
-
