### ISSUE TITLE
Celestia Kurtosis Package

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1803]
## Current Status
edit Oct 4, 2024
The Celestia DA kurtosis package MVP is working. The default is running a light node on arabica. 
This has been tested with the GM tutorial. 
Updating docs is primarily blocked on the package using a custom docker image for node until they release a new version with the docker fix. 
---

```[tasklist]
### Tasks
- [x] Confirm GM tutorial with celestia light node
- [x] Confirm GM tutorial with celestia light node in docker
- [x] Confirm GM tutorial with celestia light node kurtosis package
- [ ] https://github.com/celestiaorg/celestia-node/pull/3808
- [x] Verify GM tutorial with kurtosis submitting celestia target
- [ ] https://github.com/rollkit/gm/pull/126
- [ ] Update Docs (blocked on Celestia Node Release that includes fix from node #3808
```

Updates to GM to pull in the celestia DA:  https://github.com/rollkit/gm/pull/126

Celestia DA package repo: ~https://github.com/MSevey/celestia-da-node-package~ --> https://github.com/rollkit/kurtosis-celestia-da-node
```[tasklist]
### Follow Ups
- [ ] Persistent Storage for kurtosis package
- [ ] Faucet in kurtosis
```

**Comment by MSevey** [comment]
## Update
Currently dealing with an issue connecting to a celestia node in docker. I've been testing running the celestia light node in docker and running the GM tutorial against it to validate that all the commands work prior to moving to kurtosis. 

However I keep getting connection refused messages. 
```
error while initializing BlockManager: RPC client error: sendRequest failed: Post "http://localhost:26658": read tcp 127.0.0.1:49362->127.0.0.1:26658: read: connection reset by peer
Error intercepting command:  failed to run entrypoint: exit status 1
```

The docker run command in the celestia docs doesn't publish any ports, so I've tested add `-p 7980:7980` and `-p 26658:26658` but with no impact.

**Comment by MSevey** [comment]
some other data points.
when running the light node directly you can curl the port and get the following
```
% curl http://0.0.0.0:26658/
{"error":{"code":-32600,"message":"Invalid request"},"id":null,"jsonrpc":"2.0"}
```
when running the light node in docker and do the same curl command you get the following:
```
% curl http://0.0.0.0:26658/
curl: (56) Recv failure: Connection reset by peer
```

**Comment by MSevey** [comment]
Adding 26658 to the exposed ports in the dockerfile and adding -p 26658:26658 to the docker command changes the error to
```
error while initializing BlockManager: RPC client error: sendRequest failed: Post "http://0.0.0.0:26658/": EOF
```
just adding the -p flag to the docker run command has the same result.

**Comment by MSevey** [comment]
Updated docker command to get GM working
```
docker run -p 26658:26658 -e NODE_TYPE=$NODE_TYPE -e P2P_NETWORK=$NETWORK \
	-v /Users/matt/.docker_data/celestia-light-arabica:/home/celestia \
    ghcr.io/celestiaorg/celestia-node:v0.18.1-arabica \
    celestia $NODE_TYPE start --core.ip $RPC_URL --p2p.network $NETWORK
```

### Ports
```
-p 26658:26658
```
Only 2121 is exposed by default in the celestia node docker file. As such we need to use the `-p` flag to expose the ports on run time. 
This resolved the first error: 
```
error while initializing BlockManager: RPC client error: sendRequest failed: Post "http://localhost:26658": read tcp 127.0.0.1:49362->127.0.0.1:26658: read: connection reset by peer
```

### Node Config
The next error was this: 
```
error while initializing BlockManager: RPC client error: sendRequest failed: Post "http://0.0.0.0:26658/": EOF
```
And you could see it with curl as well. [see example above](https://github.com/rollkit/rollkit/issues/1803#issuecomment-2389614549)

For this the celestia da node config needed to be updated for the url being used for the RPC. This was 2 part. 
First we needed to persist the data itself in order to access the node config:
```
-v /Users/matt/.docker_data/celestia-light-arabica:/home/celestia 
```
In this `/Users/matt/.docker_data/celestia-light-arabica` is the folder I created on my local machine to store the data and `/home/celestia` is the folder in the docker container where node data is stored. 

After doing this, the `config.toml` file for the node needs to be modified from this:
```
[RPC]
  Address = "localhost"
  Port = "26658"
  SkipAuth = false
```
to this:
```
[RPC]
  Address = "0.0.0.0"
  Port = "26658"
  SkipAuth = false
```
This is because the docker networking is mapping to 0.0.0.0 which localhost will not auto forward to in this situation.

**Comment by MSevey** [comment]
Next steps for getting it working in kurtosis.

- [ ] Dynamically set Auth Token
- [ ] Dynamically set DA height
- [ ] Dynamically update the RPC address in the node config file

**Comment by MSevey** [comment]
Updated docker command
```
docker run -p 26658:26658 -e NODE_TYPE=$NODE_TYPE -e P2P_NETWORK=$NETWORK \
    --rm --name celestia-$NODE_TYPE-$NETWORK \
    -v /Users/matt/.docker_data/celestia-light-arabica:/home/celestia \
    ghcr.io/celestiaorg/celestia-node:v0.18.1-arabica \
    celestia $NODE_TYPE start --core.ip $RPC_URL --p2p.network $NETWORK
```

**Comment by MSevey** [comment]
need to initialize the cel_key and fund the address of the light node

**Comment by MSevey** [comment]
Current long term blocker is how to persist data with the kurtosis packages. 

Shouldn't be a blocker for the tutorials as starting the node and rolling fresh each time isn't too big a deal.

**Comment by MSevey** [comment]
Closing due to issue with persisted data on kurtosis.
