### ISSUE TITLE
[EPIC] Support ZK proofs of the EVM + IBC client in Rollkit

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/rollkit#1860]
Rough steps:
- [ ]  PoC with Reth directly working with Rollkit
- [ ] Proof generation triggering sidecar process
- [ ] Send State Proofs + Merkle Inclusion Proofs + Blob Inclusion Proof to the IBC relayer
- [ ] EVM verifier
- [ ] Celestia ZK Accounts compatibility

**Comment by Manav-Aggarwal** [comment]
For now, the PoC with Reth directly working with Rollkit can be the same as https://rollkit.dev/tutorials/beaconkit

This is because the proof generation sidecar process just needs an RPC and a block number as an input. These proofs per block are then put in a Range program to get a proof for a range of blocks and then run in an aggregator program that gets a proof for a larger range of blocks that is posted on the destination chain. Reference diagram:
![image](https://github.com/user-attachments/assets/61cdec23-777e-4f85-9591-e8d4427958c5)

We should able to reuse the Range Program and Aggregation program from the [op-succinct docs](https://succinctlabs.github.io/op-succinct/architecture.html).

For a withdrawal request from the rollup to a destination chain, we'd construct a separate program that verifies the MPT storage proof of a message in a state root already proven on the destination chain. [Proof verification code in Rust h/t Union](https://github.com/unionlabs/union/tree/main/lib/ethereum-verifier). We'd then send a proof of this program to a destination chain to process a transfer.

I'm not sure if the Blob inclusion proof is something the rollup needs to provide when bridging to Celestia necessarily since Celestia already has that information but it might be better to do to standardize the IBC client for other chains.

**Comment by Manav-Aggarwal** [comment]
Code pointers
E2E tests
Shows step-by-step with manual relaying of packets.
The main version currently uses a dummy light client on the cosmos side. It will soon be switched out with the union light client shortly (will let you know)
https://github.com/cosmos/solidity-ibc-eureka/blob/main/e2e/interchaintestv8/ibc_eureka_test.go
Union library for Ethereum verification (including membership and non-membership
https://github.com/unionlabs/union/blob/4e987f48d90af728cda09a992b2ea51220a43f33/lib/ethereum-verifier/src/verify.rs#L303
Light client examples for ibc-go
I think an easy example to start with might be the solo machine light client. It has a pretty simple model that just verifies a signature, so the structure can be reused fairly easily and just replaced with your own stuff:
https://github.com/cosmos/ibc-go/tree/main/modules/light-clients/06-solomachine
The dummy client is the bare minimum implementation:
https://github.com/cosmos/ibc-go/tree/poc-solidity-ibc-eureka-wasm/modules/light-clients/00-mock
The interchain attestation light client can also be useful to look at as it is a standalone light client written from scratch:
https://github.com/cosmos/interchain-attestation/tree/main/core/lightclient
Keep in mind that since these are just Cosmos SDK modules, there is some proto files as well that is used to generate the stored values (client state and consensus state)
Operator
The operator is doing proof generation and relaying. It works as a CLI with a few different modes. It can just run in a loop updating headers (i.e. queuing headers, creating proofs and submitting them to the light client Solidity contract) or it can execute specific SP1 programs and generate fixtures (which we use for testing)
https://github.com/cosmos/sp1-ics07-tendermint/tree/main/operator
Take a look at the root README to see how to build and run different parts of this.
Just to give a quick intro to the structure.
The SP1 programs themselves are under the “programs” folder
The operator has different runners which are triggered by the different CLI commands.
The runners take in input, makes any RPC calls it needs (to get headers and so on) and uses the SP1 programs to create proofs (and in some cases fixtures for Solidity, used by tests at the moment)

**Comment by Manav-Aggarwal** [comment]
https://github.com/invocarnau/succint-zk-residency/tree/main/fep-type-1

**Comment by Manav-Aggarwal** [comment]
Example of proving transaction inclusion in a zkvm from Risc-Zero: 

> https://github.com/risc0/demos/tree/tx_inclusion (ignore the base branch, just needed somewhere to push where you can see)
> 
> There are some small hacks with serialization given alloy Headers serde impl is broken for non self describing serialization protocols, but this should roughly show the flow of how this could work.
> 
> All this does is pull the latest block from ethereum, prepare the proof, pass in the inclusion proof with the block header, and prove that the inclusion proof is valid all the way to the block header.

**Comment by Manav-Aggarwal** [comment]
![Rollkit to Celestia](https://github.com/user-attachments/assets/2f226f3b-d3d1-499c-b241-67bba221473e)

**Comment by tac0turtle** [comment]
closing this as its unclear where this got left off but it wont be added here
