### ISSUE TITLE
Tutorial Testing

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1919]
```[tasklist]
### Tasks
- [ ] Quick start
- [ ] Quick start custom (docker, flags, etc)
- [ ] Docker compose local services
- [ ] ignite how to guide
- [ ] Update Dockerfile entrypoint rollkit CMD start
```

**Comment by MSevey** [comment]
## Status Update
Experimenting with the ignite how to guide to add these steps into CLI so that we have confidence that the ignite flow always works. 

This would then allow us to add the DA and Sequencing to this testing. 

Currently running into issues with install ignite in the ci because of the telemetry prompt
