### ISSUE TITLE
Fraud Proofs Prototype

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#514]
This is a tracking issue for everything related to fraud proofs. I'll link issues below.

ADR:
- [x] #617

Discussion:
- [x] https://github.com/celestiaorg/rollmint/issues/132

Rollmint:
- [x] #499
- [x] #408
- [x] #387 
- [x] #388
- [x] #389
- [x] #385
- [x] #438 
- [x] #335 
- [x] #10 
- [x] #4 
- [x] #6
- [x] #552 

Cosmos-SDK:
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/195
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/196
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/231
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/245
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/249
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/252
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/253
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/255
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/257
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/258
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/259
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/265
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/266
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/269
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/271
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/273
- [x] https://github.com/celestiaorg/cosmos-sdk-rollmint/issues/2
- [x] https://github.com/celestiaorg/cosmos-sdk-rollmint/issues/5
- [x] https://github.com/celestiaorg/cosmos-sdk-rollmint/issues/9
- [x] https://github.com/celestiaorg/cosmos-sdk-rollmint/issues/11

Tendermint:
- [x] https://github.com/celestiaorg/tendermint/issues/4
- [x] https://github.com/celestiaorg/tendermint/issues/62
- [x] https://github.com/celestiaorg/tendermint/issues/68
- [x] https://github.com/celestiaorg/tendermint/issues/190
