### ISSUE TITLE
Saving DA Message Commitment to Header

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#613]
- [ ] Define Commitment endpoint
- [ ] Create node endpoint for getting Commitments
- [ ] Implement Commitment method in open-rpc
- [ ] Extend DA interface to support DA message Commitments

**Comment by Manav-Aggarwal** [comment]
Duplicate: https://github.com/rollkit/rollkit/issues/1174
