### ISSUE TITLE
Fix CI issues

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#618]
- [x] https://github.com/celestiaorg/ephemeral-cluster/issues/31
- [x] https://github.com/celestiaorg/rollmint/issues/401
- [x] https://github.com/celestiaorg/go-cnc/issues/33
- [x] https://github.com/celestiaorg/go-cnc/pull/36
