### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#621]
This issue is a draft. Code-coverage pain points will be updated by @tzdybal.

- [x] #1268

types:
- [ ] Create test for `types/Header.UnmarshalBinary`
- [ ] Create test for `types/Data.MarshalBinary`

node:
- [ ] Create test for `node/Node.GetGenesis`
- [ ] Create test for `node/Node.newCommitValidator`
- [ ] Create test for `node/Node.newFraudProofValidator`

da:
- [ ] Create test for `da/celestia/mock/Server.writeError`

p2p:
- [ ] Create test for `p2p/Client.GossipCommit`
- [ ] Create test for `p2p/Client.GossipFraudProof`
- [ ] Create test for `p2p/Ciient.Addrs`
- [ ] Create test for `p2p/Client.Peers`

## Functions/methods with missing coverage
Significant amounts of uncovered code; basic error handling not taken into account.

- [ ] types/SignedHeader.ValidateBasic
- [ ] da/celestia/mock/appendToShares
- [ ] block/updateState
- [ ] config/GetNodeConfig

**Comment by nashqueue** [comment]
Moved rpc/client/Client and rpc/json/service to https://github.com/rollkit/rollkit/issues/1268

**Comment by Manav-Aggarwal** [comment]
Needs to be updated

**Comment by tac0turtle** [comment]
this will be handled in a testing sprint as the repo is changing this issue becomes more and more outdated
