### ISSUE TITLE
Local devnet

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#691]
Currently there is no one, standardized way to run a local devnet for CI and development / testing purposes.
Existing solutions are:
 * ephemeral cluster
 * docker compose setup from go-cnc

There are issues with both of them, this is why we would like to provide simple, easy to use solution, that allows to spin up Celestia devnet in single command.

Proposed solution is to build a docker image using multistage build, pulling binaries from official images of celestia-app and celestia-node. Both app and node should be started in a way similar to go-cnc setup. 

Desired properties:
* single command to spin up and expose Celestia Node API and Gateway
* no docker networks, no docker volumes - to avoid issues where pruning is required
* everything is scripted as much as possible - for maintainability
* both app and node should be re-initialized on container start; no hardcoded configs, genesis files, etc
* ideally to update node/app versions, we should only change versions of source images (except the cases with breaking changes in CLI interface)
* to keep things simple, we can reuse validator key in celestia-node, to ensure it has a lot of allocated tokens
* all endpoints of both node and app should be exposed
* minimal setup consists of celestia-app + celestia node in `bridge` mode
* versioning: we're interested mostly in celestia-node version, so we should use it for versioning; for each celestia-node version corresponding celestia-core versions should be used
* we should start with manual versioning, later we can think of integrating this with CI (for example to automatically test compatibility of released versions of core/app and node)

Tasks:

- [x] Create repository for local devnet project
- [x] #692
- [x] https://github.com/celestiaorg/local-celestia-devnet/issues/4
- [x] https://github.com/celestiaorg/local-celestia-devnet/issues/5
