### ISSUE TITLE
Move to rollkit

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#697]
- [x] Configure Access Right in rollkit org @MSevey 
- [x] Move to rollkit repo
- [x] Finish Prs before renaming files
- [x] #704
- [x] Move IVAL repository 
- [x] Move ICS23 repository 
- [x] Move Tendermint repository
- [x] Move Rollmit Cosmos-sdk
- [x] rollkit/cosmos-sdk#19
- [x] rollkit/cosmos-sdk#20
- [x] [Update Scripts and Tutorials from the Docs](https://github.com/rollkit/docs/pull/82)

**Comment by MSevey** [comment]
@nashqueue you mean the rollkit org? https://github.com/rollkit

For that I'd need @liamsi to make me an owner so I can take care of all the set up needs.

**Comment by nashqueue** [comment]
Yes thanks for the comment I meant rollkit org.

**Comment by tzdybal** [comment]
Just like: https://github.com/celestiaorg/rollmint/issues/659
