### ISSUE TITLE
Use fraud module from celestia-node

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#746]
Celestia Node implemented a very generic module to sync & store all kinds of fraud proofs.
This module potentially could be extracted as common dependency for celestia-node and rollkit.

Required changes:
- celestia-onde side:
  - [x] #756
  - [x] Extract `fraud` package to `go-proof` repository
  - [x] Use `go-proof` instead of `libs/fraud`
- rollkit:
  - [x] #892
  - [x] #893
  - [x] #894
  - [ ] #933
  - [x] #895
  - [ ] Integrate current fraud proof handling with go-proof validation logic
  - [ ] #932
 - Integration Tests:
 - [ ] ...

Required cross-team communication:
 - We need to have declaration from both @Wondertan and @renaynay that they are OK with proposed changes and they will actually accept  use of `go-proof` package in `celestia-node`. 
 
 Alternative naming: `go-proof` might as well be named `go-fraud` (sus!) or `go-fraudproof` (long).

**Comment by Wondertan** [comment]
There is one more thing that would need to be done: https://github.com/celestiaorg/celestia-node/issues/1759

Currently, fraud package hardcodes the BEFP type string, and there are code places that depend on it. Instead, we should move it to the place where BEFP[ is defined ](https://github.com/celestiaorg/celestia-node/blob/main/share/eds/byzantine/bad_encoding.go#L17-L21)and make fraud pkg implementation specifics free.

**Comment by tzdybal** [comment]
It would also be cool to actually switch to go-header before moving from `*ExtendedHeader` to `Header` interface.

**Comment by Wondertan** [comment]
I agree
