### ISSUE TITLE
EPIC: Implement Light Client Methods

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#832]
Currently, the Light Node is just a skeleton and the methods inside the light node panic. We need to decide which methods we support and implement them. 

- [ ] Implement ABCIInfo in Light Client
- [ ] Implement ABCIQuery in Light Client
- [ ] Implement ABCIQueryWithOptions in Light Client
- [ ] Implement BroadcastTxCommit in Light Client
- [ ] Implement BroadcastTxAsync in Light Client
- [ ] Implement BroadcastTxSync in Light Client
- [ ] Implement Subscribe in Light Client
- [ ] Implement Unsubscribe in Light Client
- [ ] Implement Genesis in Light Client
- [ ] Implement GenesisChunked in Light Client
- [ ] Implement BlockchainInfo in Light Client
- [ ] Implement NetInfo in Light Client
- [ ] Implement DumpConsensusState in Light Client
- [ ] Implement ConsensusState in Light Client
- [ ] Implement ConsensusParams in Light Client
- [ ] Implement Health in Light Client
- [ ] Implement Block in Light Client
- [ ] Implement BlockByHash in Light Client
- [ ] Implement BlockResults in Light Client
- [ ] Implement Commit in Light Client
- [ ] Implement Validators in Light Client
- [ ] Implement Tx in Light Client
- [ ] Implement TxSearch in Light Client
- [ ] Implement BlockSearch in Light Client
- [ ] Implement Status in Light Client
- [ ] Implement BroadcastEvidence in Light Client
- [ ] Implement NumUnconfirmedTxs in Light Client
- [ ] Implement UnconfirmedTxs in Light Client
- [ ] Implement CheckTx in Light Client

After deciding on each Method we should write an ADR to have a record of each descsion. 

- [ ] Write ADR on the Light Client Implementation

**Comment by tac0turtle** [comment]
closing this but will open a new issue on light clients
