### ISSUE TITLE
EPIC: Move from go-cnc to OpenRPC

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#850]
```[tasklist]
### Tasks
- [x] Create a new repository celestia-openrpc
- [ ] https://github.com/rollkit/local-celestia-devnet/issues/32
- [x] Copy types from Node to go-openrpc so we don`t have a dependency on node Reference: https://github.com/distractedm1nd/dn-client
- [ ] https://github.com/rollkit/celestia-openrpc/issues/6
- [ ] https://github.com/rollkit/celestia-openrpc/issues/7
- [x] Implement jsonrpc client for DA methods that we use (submit pfb, namespace shares/data)
- [ ] https://github.com/rollkit/rollkit/issues/979
- [ ] https://github.com/rollkit/rollkit/issues/1075
- [ ] https://github.com/rollkit/celestia-openrpc/issues/25
```

```[tasklist]
### Bugs
```

**Comment by nashqueue** [comment]
@tzdybal Let's figure out what remains in this EPIC and link outstanding issues from celestia-openrpc for example, to close this issue.
