### ISSUE TITLE
MEGA EPIC: Increase Developer Experience in Rollkit

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#859]
This Issue tracks all Issues&Epics to increase developer experience for internal and external developers. If you have any suggestions on increasing developer experience, make an issue with a suggestion or a feature request, and we will add it to this collection.

Docker: 
- [x] https://github.com/celestiaorg/devops/issues/115
- [x] https://github.com/celestiaorg/devops/issues/117
- [x] https://github.com/celestiaorg/devops/issues/125

CI & Automation:
- [x] https://github.com/celestiaorg/devops/issues/111
- [x] https://github.com/celestiaorg/devops/issues/112
- [x] #804 
- [x] #491 

Testing:
- [x] https://github.com/celestiaorg/devops/issues/116
- [x] https://github.com/celestiaorg/devops/issues/129
- [x] https://github.com/celestiaorg/devops/issues/122

Modularity & Interoperability
- [ ] https://github.com/rollkit/rollkit/issues/744
- [x] https://github.com/rollkit/rollkit/issues/745
- [x] https://github.com/rollkit/rollkit/discussions/755
- [ ] General Sequencing API 

Documentation:
- [x] #921

**Comment by Manav-Aggarwal** [comment]
Related: https://github.com/rollkit/docs/issues/356
