### ISSUE TITLE
[EPIC] Integration tests for cosmos-sdk App & CosmWasm Rollup

### ISSUE THREAD

**Issue by Bidon15** [rollkit/rollkit#920]
Introduction 🧐 
---

As @smuu will be taking charge of https://github.com/celestiaorg/devops/issues/129, 
this is a breakdown of initial work that we need to do. 

Ideas to start with 📝 
---

It will be beneficial if we can check that a running rollup can have the same functionality as the L1 version of it, such as: 

```[tasklist]
### Tasks
- [ ] Simple TXs (send, multi-send)
- [ ] Staking
- [ ] Queries IP:Ports of the node (grpc/rpc/rest/etc.)
```

Implementation
---

We can use this https://github.com/celestiaorg/devops/issues/291 when the first iteration of the framework comes out

- [ ] Ideally this epic should cover tests that are executed on every PR 
- [ ] Tests should be short-lived 
- [ ] using local-devnet docker image makes sense as a base assumption that DA is operable
