### ISSUE TITLE
[EPIC] Celestia Mainnet Release Compatibility

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#951]
Once v1 of celestia app and node have been released we should coordinate a release to ensure we are compatible. 

https://github.com/celestiaorg/celestia-app/releases

https://github.com/celestiaorg/celestia-node/releases

```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/1002
- [ ] https://github.com/rollkit/rollkit/issues/1004
- [ ] https://github.com/rollkit/rollkit/issues/1003
- [ ] https://github.com/rollkit/rollkit/issues/1013
```

**Comment by MSevey** [comment]
@nashqueue this might be a good issue to track celestia compatibility.

We can turn this into an EPIC and track some of the RC compatibility here.

**Comment by nashqueue** [comment]
Added process and compatibility matrix to readme
