### ISSUE TITLE
P2P Blocksync tracking Issue

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#966]
This is a tracking issue for the design document.

```[tasklist]
### Tasks
- [x] Add a Section to document the Specification of what we need to do in Header Verification
- [x] Add a Section to discuss Block data verification and if full Nodes should only gossip after execution or before
- [x] Adding any learning we had from go-header, go fraud and Bitswap
- [x] Document disallowing BroadcastTransactionCOmmit
- [x] Where should we wait for the timeout?
- [x] How does a timeout affect the syncing logic?
```

**Comment by Manav-Aggarwal** [comment]
Closed, document [here](https://www.notion.so/celestiaorg/P2P-Blocksync-Design-Document-6b81b58e3fda4b229960abb2c862e18b?pvs=4).
