### ISSUE TITLE
Reimplement `da/celestia` using `rollkit/celestia-openrpc`

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#979]
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/rollkit/issues/995
- [x] Add OpenRPC client instance to da/celestia
- [ ] https://github.com/rollkit/rollkit/issues/980
- [x] Reimplement `SubmitBlock` method
- [x] Reimplement `CheckBlockAvailability` method
- [ ] Reimplement `RetrieveBlocks` method
- [x] Remove go-cnc dependency
```

**Comment by tzdybal** [comment]
Proposition of work plan:
1. Start by adding dependency and token and openrpc client instance to da/celestia
2. Implement each method separately (can be parallelized!)
3. Remove go-cnc dependency

**Comment by tuxcanfly** [comment]
Working on adding mock handlers for the new endpoints.
