### ISSUE TITLE
EPIC: P2P-Blocksync

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#983]
```[tasklist]
### Tracking Issues around Design
- [ ] #966
- [ ] https://github.com/rollkit/rollkit/issues/984
- [ ] #1076
- [ ] https://github.com/rollkit/rollkit/issues/1031
- [ ] https://github.com/rollkit/rollkit/issues/1110
```

**Comment by Manav-Aggarwal** [comment]
Closing in favor of keeping just https://github.com/rollkit/rollkit/issues/1110 open.
