### ISSUE TITLE
[EPIC] P2P Blocksync Tracking Issue: Phase 1

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#984]
```[tasklist]
### Implementation
- [ ] https://github.com/rollkit/rollkit/issues/1005
- [x] https://github.com/rollkit/rollkit/issues/1021
- [ ] https://github.com/rollkit/rollkit/issues/1101
- [x] https://github.com/rollkit/rollkit/issues/1053
- [ ] https://github.com/rollkit/rollkit/issues/1174
```

See [Phase 1 design](https://www.notion.so/celestiaorg/P2P-Blocksync-Design-Document-6b81b58e3fda4b229960abb2c862e18b?pvs=4#f9acce9993cc4aa896449092fc9dfe92) for more details.

**Comment by MSevey** [comment]
Making a note here for planning out how we implement the PRs.

Currently we want to try and release this as v0.11.x of rollkit. We have v0.9.x and v0.10.x planned so let's make sure that we implement this in a way that doesn't break current blocksync.

Since most of Phase 1 is new functionality, that shouldn't be a problem, and then once most of the key components are implemented we can do a final PR and makes any changes to the current blocksync as necessary.

cc @Manav-Aggarwal
