### ISSUE TITLE
Update ADR 009 after P2P Blocksync

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#989]
```[tasklist]
### Tasks
- [ ] Update the Data Struct to be accurate
- [ ] Update the State Fraud Proof Sequence Diagram with new P2P Blocksync
- [ ] Update Comment "// Only one have of these three can be non-nil"
- [ ] Make sure that verification and split into stages matches the stages in the implementation.
```
