### ISSUE TITLE
[EPIC] Upgrade Rollkit to Cosmos SDK 0.47.x compatibility

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#998]
Phase 1: Cosmos SDK 0.47.x w/ cometbft 0.37.x (for Sugra)

- [x] Sync rollkit/cometbft (branch: [rollkit/v0.37.1](https://github.com/rollkit/cometbft/commits/rollkit/v0.37.1)) to cometbft:v0.37.1
- [x] Pull cosmos/cosmos-sdk:release/v0.47.x to rollkit/cosmos-sdk (https://github.com/rollkit/cosmos-sdk/commits/release/v0.47.x-rollkit)
- [x] Replace tendermint with cometbft (https://github.com/rollkit/rollkit/pull/793)
- [x] Upgrade rollkit mempool from old tendermint copy to cometbft (https://github.com/rollkit/rollkit/pull/991)
- [x] Draft rollkit release (0.10.x) using diego/cometbft-0.37.1-mempool branch to test the cosmos-sdk:release/v0.47.x
- [x] Add rollkit changes to cosmos-sdk:release/v0.47.x with draft release and also use rollkit/cometbft (branch: rollkit/v0.37.1)
- [x] Test gm tutorial 

Phase 2: Cosmos SDK 0.47.x w/ cometbft 0.38.x (for Siralop)

- [x] Upgrade rollkit mempool to bring the latest breaking changes from cometbft 0.38.x
- [x] Update rollkit to use rollkit/cometbft (branch: rollkit/v0.38.0-alpha.2)
- [x] Draft rollkit release (0.10.x) to test the cosmos-sdk:release/v0.47.x with cometbft 0.38.x
- [x] Add rollkit changes to cosmos-sdk:release/v0.47.x with draft release and also use rollkit/cometbft (branch: rollkit/v0.38.0-alpha.2)
- [ ] Test gm tutorial

**Comment by MSevey** [comment]
Key things to note from the plan. 

Rollkit v0.9.x will be cometbft v0.37.x and cosmos-sdk v0.47.x

Rollkit v0.10.x will be cometbft v0.38.x and cosmos-sdk v0.47.x

Part of releasing v0.9.x should be stating what, if any, updates we plan to make to that release.  I would recommend we start from an expectation that we won't be applying any updates to v0.9.x, we are simply establishing a stable release for those needing cosmos-sdk v0.47.x and cometbft v0.37.x. If there are bugs or updates needed, the expectation should be that people are upgrading to rollkit v0.10.x or higher.

**Comment by Manav-Aggarwal** [comment]
Can we mark this as closed? @gupadhyaya

**Comment by gupadhyaya** [comment]
i think we can close this epic after the custom GM tutorial (should be done this week).

**Comment by Manav-Aggarwal** [comment]
Closing since Rollkit supports Cosmos SDK 0.50.6+ now
